### ISSUE TITLE
Read commit log

### ISSUE THREAD

**Issue by llorllale** [llorllale/go-gitlint#4]

**Comment by 0pdd** [comment]
@llorllale 4 puzzles [#10](https://github.com/llorllale/go-gitlint/issues/10), [#11](https://github.com/llorllale/go-gitlint/issues/11), [#12](https://github.com/llorllale/go-gitlint/issues/12), [#9](https://github.com/llorllale/go-gitlint/issues/9) are still not solved.

**Comment by llorllale** [comment]
Done in PR #4

**Comment by 0pdd** [comment]
@llorllale 3 puzzles [#10](https://github.com/llorllale/go-gitlint/issues/10), [#11](https://github.com/llorllale/go-gitlint/issues/11), [#9](https://github.com/llorllale/go-gitlint/issues/9) are still not solved; solved: [#12](https://github.com/llorllale/go-gitlint/issues/12).

**Comment by 0pdd** [comment]
@llorllale 3 puzzles [#10](https://github.com/llorllale/go-gitlint/issues/10), [#11](https://github.com/llorllale/go-gitlint/issues/11), [#23](https://github.com/llorllale/go-gitlint/issues/23) are still not solved; solved: [#12](https://github.com/llorllale/go-gitlint/issues/12), [#9](https://github.com/llorllale/go-gitlint/issues/9).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#10](https://github.com/llorllale/go-gitlint/issues/10), [#11](https://github.com/llorllale/go-gitlint/issues/11) are still not solved; solved: [#12](https://github.com/llorllale/go-gitlint/issues/12), [#23](https://github.com/llorllale/go-gitlint/issues/23), [#9](https://github.com/llorllale/go-gitlint/issues/9).
